import { ClerkProvider } from "@clerk/nextjs";

import type { Metadata } from "next";

import OnlineStatusProvider from "@/components/providers/OnlineStatusProvider";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import ConvexClientProvider from "@/providers/ConvexClientProvider";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CallProvider } from "@/hooks/useCalls";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div
          id="call_room_portal"
          className="flex items-center justify-center z-[100000]"
        ></div>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ClerkProvider>
            <CallProvider>
              <ConvexClientProvider>
                <OnlineStatusProvider>
                  <TooltipProvider>{children}</TooltipProvider>
                  <Toaster position="top-center" richColors />
                </OnlineStatusProvider>
              </ConvexClientProvider>
            </CallProvider>
          </ClerkProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
